### ISSUE TITLE
ungefahrene streckenabschnitte

### ISSUE THREAD

**Issue by lukruh** [telebotter/tour#21]
was nicht geradelt wurde, sollte gestrichelt werden, und idealerweise auch in zukuenftiger routen rechnung (gesamt steigung km schnitt etc) ignroiert.. dazu muss es geschnippselt werden und ein property kriegen.
Vorläufig könnte das durch start und endzeit angaben gehen, ein manuelles LineString zu erstellen.

Neues Issue: Langfristig, würde es sich vlt. lohnen sonen simplen mapeditor zu basteln, in dem man die tracks nachtraeglich anpassen kann manuell tags setzen und punkte auswaehlen, an denen tracks aufgebrochen werden etc.. aber das sollte dann alles nach der normalen tour seite kommen.. 
Bindings zu gpsies und/oder brouter wären natürlich krass premium..

**Comment by hendricokakiko** [comment]
denke das anpassen der gpx's wird seltener vorkommen mit dem gps logger, und wenn dan kann mans halt auch per hand/skript/secundär programm ändern. für eine tour pro jahr glaube ich nicht das sich ein eigener mapeditor lohnt

aber zugfahrten/flüge/bustouren anders darzustellen wäre der hammer!

**Comment by lukruh** [comment]
ja ich denke auch, die json oder csv dateien sind zu lang um sie per hand zu bearbeiten, aber sehr handlich um sie einfach mit code in der konsole zu manipulieren.. das reicht ja ein zwei scripte zu haben die die csv datei einlsen, evt. daten reduzieren (weniger als 50m abstand loeschen oder so).. map editor steht erstmal  am aller aller untensten auf der liste ;)

aber ich passe grad die db struktur etwas an, dass eine tour nichtmehr ein json feld `track` hat, wo die kompletten (geo)tourdaten drin sind (etappen, farben, linien stil etc).. sondern `track` ein model ist, welches wiederum einzelne `segments` hat und die segments haben dann ein json field, welches eine liste aus koordinaten enthaelt (tagesetappe) und zusaetlich ein boolean `transfer`, der benutzt werden kann um zB den linenstil zu aendern. Auserdem kann dort ein FileField hinterlegt sein um die original/bearbeitete csv datei zuzu ordnen.

Der vorteil liegt denke ich auf der hand.. statt in 10k zeilen langen json dateien fehlende klammern zu suchen, kann man direkt eigenschaften für einzelne segmente setzen. Ausserdem passt das ganz gut zum 1 csv-file pro tag konzept. In der nachbearbeitung, kann man dann zB vor dem hochladen eine csv datei an entsprechender stelle (uhrzeit oder etwas rumgefrickel mit koordinaten) splitten, bzw man baut eine funktion, die ein segment im nachhinein in zwei einzelsegmente unterteilt. So kann man dann auch kleiner einheiten als tagestouren in einer anderen farbe darstellen.. 

So koennen auch einzeltracks direkt hochgeladen werden, ohne dass man die csvs noch zusammen packen muss, was denke ich sehr handyfreundlich sein wird :)

**Comment by lukruh** [comment]
da die datenbank schon inhalt hat und ich den aktuell funktionierenden code nicht kaputt machen will ;) hab ich erstmal nen branch erstellt zum experimentieren.. damit man parallel noch bugs fixen kann, ohne halb fertigen code rein zu pullen

**Comment by hendricokakiko** [comment]
bester man! klingt sau clever!

**Comment by lukruh** [comment]
#20

**Comment by lukruh** [comment]
check
